### ISSUE TITLE
getAmbientPressureOffset without a setAmbientPressureOffset

### ISSUE THREAD

**Issue by aimgo** [adafruit/Adafruit_SCD30#19]
Library features a method to get pressure offset without setting. Altitude overwrites this offset? What gives? Is this a way to set the offset?

**Comment by caternuson** [comment]
It's unclear what the issue is here. This all the behavior specified in the SCD30 datasheet.

The pressure compensation and altitude are essentially two different ways of specifying the same correction. The general idea is if you have a separate pressure sensor, that could be used to provide a real time value for correction. Otherwise, you can specify an altitude for a nominal (probably based on standard atmosphere) correction.

**Comment by aimgo** [comment]
> It's unclear what the issue is here. This all the behavior specified in the SCD30 datasheet.
> 
> The pressure compensation and altitude are essentially two different ways of specifying the same correction. The general idea is if you have a separate pressure sensor, that could be used to provide a real time value for correction. Otherwise, you can specify an altitude for a nominal (probably based on standard atmosphere) correction.

I've read the documentation as well. It says there is a pressure offset,  and there's a method to get that pressure offset but not to set it. Why would I convert the pressure into altitude and introduce a margin of error? Why write the 'getPressureOffset' in the first place if it's the same as altitude? There is an open pull request that addresses this issue, perhaps by looking at the solution the issue will be made clear.

**Comment by caternuson** [comment]
Those answers would have to come from the sensor manufacturer.

Do you have a specific code example that can demonstrate an issue?

**Comment by caternuson** [comment]
Closing due to lack of response. Can reopen if code example demonstrating issue can be provided.
